### PR TITLE
Merge pull request #4 from laurents17/countries

### PR DESCRIPTION
**Pull request by laurents17**
Still having issues with getting the answers and flags to display correctly on questions, edit, and delete pages, and getting the edits and deletes to actually save to the database.

### CODE REVIEW

**Comment by vegajdr** [comment]
@laurents17 I see that there is no code on this commit, did you mean to push code on this PR?

**Comment by laurents17** [comment]
@vegajdr I don't know what I did on this one but I think I ended up merging it before you got a chance to see it or something

**Comment by laurents17** [comment]
@vegajdr or I created a brand new pull request instead of creating one from a commit... would that make sense?

**Comment by vegajdr** [comment]
Ok no worries 👍

**Pull request closed without merging**
